name: regenerate
on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual triggering
  pull_request:
jobs:
  regenerate:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          package-set:
            - 'flake.*'
            - nix/package-set/generate.nix
            - nix/utils.nix
    - if: steps.changes.outputs.package-set == 'true'
      uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          accept-flake-config = true
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - if: steps.changes.outputs.template == 'true'
      uses: cachix/cachix-action@v12
      with:
        name: klarkc
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - if: steps.changes.outputs.template == 'true'
      name: regenerate nix/package-set
      run: |
        set -e
        nix build .#generator --show-trace --impure
        cp result nix/package-set/default.nix
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "build(package-set): regenerate package-set"
