name: regenerate
on:
  workflow_dispatch: # allows manual triggering
  push:
    branches:
      - update_flake_lock_action
jobs:
  test-ctl-nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v21
      with:
        extra_nix_config: |
          accept-flake-config = true
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v12
      with:
        name: klarkc
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
        set -e
        nix flake build .#package-set --show-trace --impure
        cp result nix/package-set/default.nix
    - name: Check for changes
      id: git-check
      run: |
        if [[ -z "$(git status --porcelain)" ]]; then
          echo "::set-output name=changes::false"
        else
          echo "::set-output name=changes::true"
        fi
    - name: Commit changes
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add nix/package-set/default.nix
        git commit -m "build(package-set): regenerate package-set"
